# Basic settings
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"
set -g window-status-separator " "
set -g status-position top
setw -g automatic-rename off
set -g allow-rename off

# Plugins
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_number ''
set -g @catppuccin_window_text '#[fg=#{?#{m/r:^[0-9]+$,#{window_name}},#4f5164,#7c8096}] #{p4:#{window_name}}   '
set -g @catppuccin_window_current_number ''
set -g @catppuccin_window_current_text '#[fg=#11111b] #{p4:#{window_name}}   '
set -g @catppuccin_window_current_text_color '#92b3f4'
set -g @catppuccin_window_left_separator ''
set -g @catppuccin_window_middle_separator ''
set -g @catppuccin_window_right_separator ''
set -g @catppuccin_window_current_left_separator ''
set -g @catppuccin_window_current_middle_separator ''
set -g @catppuccin_window_current_right_separator ''
set -g @catppuccin_status_left_separator '█'
set -g @catppuccin_status_right_separator ''
set -g @catppuccin_status_connect_separator 'no'
set -g @catppuccin_session_text ' #S #[bg=default] '
set -g @catppuccin_application_text ' #{pane_current_command} #[bg=default] '
set -g @catppuccin_battery_text ' #{l:#{battery_percentage}} '
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tmux/catppuccin.tmux'

# Status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/tpm/tpm'
